// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ColourMessage.proto

package com.criss.wang.entity.proto;

public final class ColourProto {
  private ColourProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ColourMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.criss.wang.entity.proto.ColourMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    boolean hasChildMessage();
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    com.google.protobuf.Any getChildMessage();
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getChildMessageOrBuilder();

    /**
     * <code>.google.protobuf.Any redMessage = 3;</code>
     */
    boolean hasRedMessage();
    /**
     * <code>.google.protobuf.Any redMessage = 3;</code>
     */
    com.google.protobuf.Any getRedMessage();
    /**
     * <code>.google.protobuf.Any redMessage = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getRedMessageOrBuilder();

    /**
     * <code>.google.protobuf.Any blueMessage = 4;</code>
     */
    boolean hasBlueMessage();
    /**
     * <code>.google.protobuf.Any blueMessage = 4;</code>
     */
    com.google.protobuf.Any getBlueMessage();
    /**
     * <code>.google.protobuf.Any blueMessage = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getBlueMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.criss.wang.entity.proto.ColourMessage}
   */
  public  static final class ColourMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.criss.wang.entity.proto.ColourMessage)
      ColourMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ColourMessage.newBuilder() to construct.
    private ColourMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ColourMessage() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ColourMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (childMessage_ != null) {
                subBuilder = childMessage_.toBuilder();
              }
              childMessage_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(childMessage_);
                childMessage_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (redMessage_ != null) {
                subBuilder = redMessage_.toBuilder();
              }
              redMessage_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(redMessage_);
                redMessage_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (blueMessage_ != null) {
                subBuilder = blueMessage_.toBuilder();
              }
              blueMessage_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(blueMessage_);
                blueMessage_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_ColourMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_ColourMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.criss.wang.entity.proto.ColourProto.ColourMessage.class, com.criss.wang.entity.proto.ColourProto.ColourMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHILDMESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.Any childMessage_;
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    public boolean hasChildMessage() {
      return childMessage_ != null;
    }
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    public com.google.protobuf.Any getChildMessage() {
      return childMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : childMessage_;
    }
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getChildMessageOrBuilder() {
      return getChildMessage();
    }

    public static final int REDMESSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.Any redMessage_;
    /**
     * <code>.google.protobuf.Any redMessage = 3;</code>
     */
    public boolean hasRedMessage() {
      return redMessage_ != null;
    }
    /**
     * <code>.google.protobuf.Any redMessage = 3;</code>
     */
    public com.google.protobuf.Any getRedMessage() {
      return redMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : redMessage_;
    }
    /**
     * <code>.google.protobuf.Any redMessage = 3;</code>
     */
    public com.google.protobuf.AnyOrBuilder getRedMessageOrBuilder() {
      return getRedMessage();
    }

    public static final int BLUEMESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.Any blueMessage_;
    /**
     * <code>.google.protobuf.Any blueMessage = 4;</code>
     */
    public boolean hasBlueMessage() {
      return blueMessage_ != null;
    }
    /**
     * <code>.google.protobuf.Any blueMessage = 4;</code>
     */
    public com.google.protobuf.Any getBlueMessage() {
      return blueMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : blueMessage_;
    }
    /**
     * <code>.google.protobuf.Any blueMessage = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBlueMessageOrBuilder() {
      return getBlueMessage();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (childMessage_ != null) {
        output.writeMessage(2, getChildMessage());
      }
      if (redMessage_ != null) {
        output.writeMessage(3, getRedMessage());
      }
      if (blueMessage_ != null) {
        output.writeMessage(4, getBlueMessage());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (childMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getChildMessage());
      }
      if (redMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRedMessage());
      }
      if (blueMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getBlueMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.criss.wang.entity.proto.ColourProto.ColourMessage)) {
        return super.equals(obj);
      }
      com.criss.wang.entity.proto.ColourProto.ColourMessage other = (com.criss.wang.entity.proto.ColourProto.ColourMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (hasChildMessage() == other.hasChildMessage());
      if (hasChildMessage()) {
        result = result && getChildMessage()
            .equals(other.getChildMessage());
      }
      result = result && (hasRedMessage() == other.hasRedMessage());
      if (hasRedMessage()) {
        result = result && getRedMessage()
            .equals(other.getRedMessage());
      }
      result = result && (hasBlueMessage() == other.hasBlueMessage());
      if (hasBlueMessage()) {
        result = result && getBlueMessage()
            .equals(other.getBlueMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasChildMessage()) {
        hash = (37 * hash) + CHILDMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getChildMessage().hashCode();
      }
      if (hasRedMessage()) {
        hash = (37 * hash) + REDMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getRedMessage().hashCode();
      }
      if (hasBlueMessage()) {
        hash = (37 * hash) + BLUEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getBlueMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.ColourMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.criss.wang.entity.proto.ColourProto.ColourMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.criss.wang.entity.proto.ColourMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.criss.wang.entity.proto.ColourMessage)
        com.criss.wang.entity.proto.ColourProto.ColourMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_ColourMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_ColourMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.criss.wang.entity.proto.ColourProto.ColourMessage.class, com.criss.wang.entity.proto.ColourProto.ColourMessage.Builder.class);
      }

      // Construct using com.criss.wang.entity.proto.ColourProto.ColourMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (childMessageBuilder_ == null) {
          childMessage_ = null;
        } else {
          childMessage_ = null;
          childMessageBuilder_ = null;
        }
        if (redMessageBuilder_ == null) {
          redMessage_ = null;
        } else {
          redMessage_ = null;
          redMessageBuilder_ = null;
        }
        if (blueMessageBuilder_ == null) {
          blueMessage_ = null;
        } else {
          blueMessage_ = null;
          blueMessageBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_ColourMessage_descriptor;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.ColourMessage getDefaultInstanceForType() {
        return com.criss.wang.entity.proto.ColourProto.ColourMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.ColourMessage build() {
        com.criss.wang.entity.proto.ColourProto.ColourMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.ColourMessage buildPartial() {
        com.criss.wang.entity.proto.ColourProto.ColourMessage result = new com.criss.wang.entity.proto.ColourProto.ColourMessage(this);
        result.name_ = name_;
        if (childMessageBuilder_ == null) {
          result.childMessage_ = childMessage_;
        } else {
          result.childMessage_ = childMessageBuilder_.build();
        }
        if (redMessageBuilder_ == null) {
          result.redMessage_ = redMessage_;
        } else {
          result.redMessage_ = redMessageBuilder_.build();
        }
        if (blueMessageBuilder_ == null) {
          result.blueMessage_ = blueMessage_;
        } else {
          result.blueMessage_ = blueMessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.criss.wang.entity.proto.ColourProto.ColourMessage) {
          return mergeFrom((com.criss.wang.entity.proto.ColourProto.ColourMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.criss.wang.entity.proto.ColourProto.ColourMessage other) {
        if (other == com.criss.wang.entity.proto.ColourProto.ColourMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasChildMessage()) {
          mergeChildMessage(other.getChildMessage());
        }
        if (other.hasRedMessage()) {
          mergeRedMessage(other.getRedMessage());
        }
        if (other.hasBlueMessage()) {
          mergeBlueMessage(other.getBlueMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.criss.wang.entity.proto.ColourProto.ColourMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.criss.wang.entity.proto.ColourProto.ColourMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any childMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> childMessageBuilder_;
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public boolean hasChildMessage() {
        return childMessageBuilder_ != null || childMessage_ != null;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public com.google.protobuf.Any getChildMessage() {
        if (childMessageBuilder_ == null) {
          return childMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : childMessage_;
        } else {
          return childMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder setChildMessage(com.google.protobuf.Any value) {
        if (childMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          childMessage_ = value;
          onChanged();
        } else {
          childMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder setChildMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (childMessageBuilder_ == null) {
          childMessage_ = builderForValue.build();
          onChanged();
        } else {
          childMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder mergeChildMessage(com.google.protobuf.Any value) {
        if (childMessageBuilder_ == null) {
          if (childMessage_ != null) {
            childMessage_ =
              com.google.protobuf.Any.newBuilder(childMessage_).mergeFrom(value).buildPartial();
          } else {
            childMessage_ = value;
          }
          onChanged();
        } else {
          childMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder clearChildMessage() {
        if (childMessageBuilder_ == null) {
          childMessage_ = null;
          onChanged();
        } else {
          childMessage_ = null;
          childMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public com.google.protobuf.Any.Builder getChildMessageBuilder() {
        
        onChanged();
        return getChildMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getChildMessageOrBuilder() {
        if (childMessageBuilder_ != null) {
          return childMessageBuilder_.getMessageOrBuilder();
        } else {
          return childMessage_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : childMessage_;
        }
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getChildMessageFieldBuilder() {
        if (childMessageBuilder_ == null) {
          childMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getChildMessage(),
                  getParentForChildren(),
                  isClean());
          childMessage_ = null;
        }
        return childMessageBuilder_;
      }

      private com.google.protobuf.Any redMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> redMessageBuilder_;
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public boolean hasRedMessage() {
        return redMessageBuilder_ != null || redMessage_ != null;
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public com.google.protobuf.Any getRedMessage() {
        if (redMessageBuilder_ == null) {
          return redMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : redMessage_;
        } else {
          return redMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public Builder setRedMessage(com.google.protobuf.Any value) {
        if (redMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          redMessage_ = value;
          onChanged();
        } else {
          redMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public Builder setRedMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (redMessageBuilder_ == null) {
          redMessage_ = builderForValue.build();
          onChanged();
        } else {
          redMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public Builder mergeRedMessage(com.google.protobuf.Any value) {
        if (redMessageBuilder_ == null) {
          if (redMessage_ != null) {
            redMessage_ =
              com.google.protobuf.Any.newBuilder(redMessage_).mergeFrom(value).buildPartial();
          } else {
            redMessage_ = value;
          }
          onChanged();
        } else {
          redMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public Builder clearRedMessage() {
        if (redMessageBuilder_ == null) {
          redMessage_ = null;
          onChanged();
        } else {
          redMessage_ = null;
          redMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public com.google.protobuf.Any.Builder getRedMessageBuilder() {
        
        onChanged();
        return getRedMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getRedMessageOrBuilder() {
        if (redMessageBuilder_ != null) {
          return redMessageBuilder_.getMessageOrBuilder();
        } else {
          return redMessage_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : redMessage_;
        }
      }
      /**
       * <code>.google.protobuf.Any redMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getRedMessageFieldBuilder() {
        if (redMessageBuilder_ == null) {
          redMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getRedMessage(),
                  getParentForChildren(),
                  isClean());
          redMessage_ = null;
        }
        return redMessageBuilder_;
      }

      private com.google.protobuf.Any blueMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> blueMessageBuilder_;
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public boolean hasBlueMessage() {
        return blueMessageBuilder_ != null || blueMessage_ != null;
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public com.google.protobuf.Any getBlueMessage() {
        if (blueMessageBuilder_ == null) {
          return blueMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : blueMessage_;
        } else {
          return blueMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public Builder setBlueMessage(com.google.protobuf.Any value) {
        if (blueMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blueMessage_ = value;
          onChanged();
        } else {
          blueMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public Builder setBlueMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (blueMessageBuilder_ == null) {
          blueMessage_ = builderForValue.build();
          onChanged();
        } else {
          blueMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public Builder mergeBlueMessage(com.google.protobuf.Any value) {
        if (blueMessageBuilder_ == null) {
          if (blueMessage_ != null) {
            blueMessage_ =
              com.google.protobuf.Any.newBuilder(blueMessage_).mergeFrom(value).buildPartial();
          } else {
            blueMessage_ = value;
          }
          onChanged();
        } else {
          blueMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public Builder clearBlueMessage() {
        if (blueMessageBuilder_ == null) {
          blueMessage_ = null;
          onChanged();
        } else {
          blueMessage_ = null;
          blueMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public com.google.protobuf.Any.Builder getBlueMessageBuilder() {
        
        onChanged();
        return getBlueMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBlueMessageOrBuilder() {
        if (blueMessageBuilder_ != null) {
          return blueMessageBuilder_.getMessageOrBuilder();
        } else {
          return blueMessage_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : blueMessage_;
        }
      }
      /**
       * <code>.google.protobuf.Any blueMessage = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBlueMessageFieldBuilder() {
        if (blueMessageBuilder_ == null) {
          blueMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBlueMessage(),
                  getParentForChildren(),
                  isClean());
          blueMessage_ = null;
        }
        return blueMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.criss.wang.entity.proto.ColourMessage)
    }

    // @@protoc_insertion_point(class_scope:com.criss.wang.entity.proto.ColourMessage)
    private static final com.criss.wang.entity.proto.ColourProto.ColourMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.criss.wang.entity.proto.ColourProto.ColourMessage();
    }

    public static com.criss.wang.entity.proto.ColourProto.ColourMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ColourMessage>
        PARSER = new com.google.protobuf.AbstractParser<ColourMessage>() {
      @java.lang.Override
      public ColourMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ColourMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ColourMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ColourMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.criss.wang.entity.proto.ColourProto.ColourMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.criss.wang.entity.proto.RedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 number = 2;</code>
     */
    int getNumber();
  }
  /**
   * Protobuf type {@code com.criss.wang.entity.proto.RedMessage}
   */
  public  static final class RedMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.criss.wang.entity.proto.RedMessage)
      RedMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RedMessage.newBuilder() to construct.
    private RedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RedMessage() {
      name_ = "";
      number_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              number_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_RedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_RedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.criss.wang.entity.proto.ColourProto.RedMessage.class, com.criss.wang.entity.proto.ColourProto.RedMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_;
    /**
     * <code>int32 number = 2;</code>
     */
    public int getNumber() {
      return number_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (number_ != 0) {
        output.writeInt32(2, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.criss.wang.entity.proto.ColourProto.RedMessage)) {
        return super.equals(obj);
      }
      com.criss.wang.entity.proto.ColourProto.RedMessage other = (com.criss.wang.entity.proto.ColourProto.RedMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getNumber()
          == other.getNumber());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.RedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.criss.wang.entity.proto.ColourProto.RedMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.criss.wang.entity.proto.RedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.criss.wang.entity.proto.RedMessage)
        com.criss.wang.entity.proto.ColourProto.RedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_RedMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_RedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.criss.wang.entity.proto.ColourProto.RedMessage.class, com.criss.wang.entity.proto.ColourProto.RedMessage.Builder.class);
      }

      // Construct using com.criss.wang.entity.proto.ColourProto.RedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        number_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_RedMessage_descriptor;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.RedMessage getDefaultInstanceForType() {
        return com.criss.wang.entity.proto.ColourProto.RedMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.RedMessage build() {
        com.criss.wang.entity.proto.ColourProto.RedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.RedMessage buildPartial() {
        com.criss.wang.entity.proto.ColourProto.RedMessage result = new com.criss.wang.entity.proto.ColourProto.RedMessage(this);
        result.name_ = name_;
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.criss.wang.entity.proto.ColourProto.RedMessage) {
          return mergeFrom((com.criss.wang.entity.proto.ColourProto.RedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.criss.wang.entity.proto.ColourProto.RedMessage other) {
        if (other == com.criss.wang.entity.proto.ColourProto.RedMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.criss.wang.entity.proto.ColourProto.RedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.criss.wang.entity.proto.ColourProto.RedMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 2;</code>
       */
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 2;</code>
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 2;</code>
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.criss.wang.entity.proto.RedMessage)
    }

    // @@protoc_insertion_point(class_scope:com.criss.wang.entity.proto.RedMessage)
    private static final com.criss.wang.entity.proto.ColourProto.RedMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.criss.wang.entity.proto.ColourProto.RedMessage();
    }

    public static com.criss.wang.entity.proto.ColourProto.RedMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RedMessage>
        PARSER = new com.google.protobuf.AbstractParser<RedMessage>() {
      @java.lang.Override
      public RedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RedMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RedMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RedMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.criss.wang.entity.proto.ColourProto.RedMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlueMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.criss.wang.entity.proto.BlueMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 number = 2;</code>
     */
    int getNumber();
  }
  /**
   * Protobuf type {@code com.criss.wang.entity.proto.BlueMessage}
   */
  public  static final class BlueMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.criss.wang.entity.proto.BlueMessage)
      BlueMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlueMessage.newBuilder() to construct.
    private BlueMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlueMessage() {
      name_ = "";
      number_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlueMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              number_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_BlueMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_BlueMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.criss.wang.entity.proto.ColourProto.BlueMessage.class, com.criss.wang.entity.proto.ColourProto.BlueMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_;
    /**
     * <code>int32 number = 2;</code>
     */
    public int getNumber() {
      return number_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (number_ != 0) {
        output.writeInt32(2, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.criss.wang.entity.proto.ColourProto.BlueMessage)) {
        return super.equals(obj);
      }
      com.criss.wang.entity.proto.ColourProto.BlueMessage other = (com.criss.wang.entity.proto.ColourProto.BlueMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getNumber()
          == other.getNumber());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ColourProto.BlueMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.criss.wang.entity.proto.ColourProto.BlueMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.criss.wang.entity.proto.BlueMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.criss.wang.entity.proto.BlueMessage)
        com.criss.wang.entity.proto.ColourProto.BlueMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_BlueMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_BlueMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.criss.wang.entity.proto.ColourProto.BlueMessage.class, com.criss.wang.entity.proto.ColourProto.BlueMessage.Builder.class);
      }

      // Construct using com.criss.wang.entity.proto.ColourProto.BlueMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        number_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.criss.wang.entity.proto.ColourProto.internal_static_com_criss_wang_entity_proto_BlueMessage_descriptor;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.BlueMessage getDefaultInstanceForType() {
        return com.criss.wang.entity.proto.ColourProto.BlueMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.BlueMessage build() {
        com.criss.wang.entity.proto.ColourProto.BlueMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ColourProto.BlueMessage buildPartial() {
        com.criss.wang.entity.proto.ColourProto.BlueMessage result = new com.criss.wang.entity.proto.ColourProto.BlueMessage(this);
        result.name_ = name_;
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.criss.wang.entity.proto.ColourProto.BlueMessage) {
          return mergeFrom((com.criss.wang.entity.proto.ColourProto.BlueMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.criss.wang.entity.proto.ColourProto.BlueMessage other) {
        if (other == com.criss.wang.entity.proto.ColourProto.BlueMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.criss.wang.entity.proto.ColourProto.BlueMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.criss.wang.entity.proto.ColourProto.BlueMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 2;</code>
       */
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 2;</code>
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 2;</code>
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.criss.wang.entity.proto.BlueMessage)
    }

    // @@protoc_insertion_point(class_scope:com.criss.wang.entity.proto.BlueMessage)
    private static final com.criss.wang.entity.proto.ColourProto.BlueMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.criss.wang.entity.proto.ColourProto.BlueMessage();
    }

    public static com.criss.wang.entity.proto.ColourProto.BlueMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlueMessage>
        PARSER = new com.google.protobuf.AbstractParser<BlueMessage>() {
      @java.lang.Override
      public BlueMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlueMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlueMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlueMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.criss.wang.entity.proto.ColourProto.BlueMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_criss_wang_entity_proto_ColourMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_criss_wang_entity_proto_ColourMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_criss_wang_entity_proto_RedMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_criss_wang_entity_proto_RedMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_criss_wang_entity_proto_BlueMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_criss_wang_entity_proto_BlueMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ColourMessage.proto\022\033com.criss.wang.en" +
      "tity.proto\032\031google/protobuf/any.proto\"\236\001" +
      "\n\rColourMessage\022\014\n\004name\030\001 \001(\t\022*\n\014childMe" +
      "ssage\030\002 \001(\0132\024.google.protobuf.Any\022(\n\nred" +
      "Message\030\003 \001(\0132\024.google.protobuf.Any\022)\n\013b" +
      "lueMessage\030\004 \001(\0132\024.google.protobuf.Any\"*" +
      "\n\nRedMessage\022\014\n\004name\030\001 \001(\t\022\016\n\006number\030\002 \001" +
      "(\005\"+\n\013BlueMessage\022\014\n\004name\030\001 \001(\t\022\016\n\006numbe" +
      "r\030\002 \001(\005B\rB\013ColourProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_com_criss_wang_entity_proto_ColourMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_criss_wang_entity_proto_ColourMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_criss_wang_entity_proto_ColourMessage_descriptor,
        new java.lang.String[] { "Name", "ChildMessage", "RedMessage", "BlueMessage", });
    internal_static_com_criss_wang_entity_proto_RedMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_criss_wang_entity_proto_RedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_criss_wang_entity_proto_RedMessage_descriptor,
        new java.lang.String[] { "Name", "Number", });
    internal_static_com_criss_wang_entity_proto_BlueMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_criss_wang_entity_proto_BlueMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_criss_wang_entity_proto_BlueMessage_descriptor,
        new java.lang.String[] { "Name", "Number", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
