// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParentMessage.proto

package com.criss.wang.entity.proto;

public final class ParentMessageProto {
  private ParentMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParentMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.criss.wang.entity.proto.ParentMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    boolean hasChildMessage();
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    com.google.protobuf.Any getChildMessage();
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getChildMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.criss.wang.entity.proto.ParentMessage}
   */
  public  static final class ParentMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.criss.wang.entity.proto.ParentMessage)
      ParentMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParentMessage.newBuilder() to construct.
    private ParentMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParentMessage() {
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParentMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (childMessage_ != null) {
                subBuilder = childMessage_.toBuilder();
              }
              childMessage_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(childMessage_);
                childMessage_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ParentMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ParentMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.criss.wang.entity.proto.ParentMessageProto.ParentMessage.class, com.criss.wang.entity.proto.ParentMessageProto.ParentMessage.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHILDMESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.Any childMessage_;
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    public boolean hasChildMessage() {
      return childMessage_ != null;
    }
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    public com.google.protobuf.Any getChildMessage() {
      return childMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : childMessage_;
    }
    /**
     * <code>.google.protobuf.Any childMessage = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getChildMessageOrBuilder() {
      return getChildMessage();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (childMessage_ != null) {
        output.writeMessage(2, getChildMessage());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (childMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getChildMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.criss.wang.entity.proto.ParentMessageProto.ParentMessage)) {
        return super.equals(obj);
      }
      com.criss.wang.entity.proto.ParentMessageProto.ParentMessage other = (com.criss.wang.entity.proto.ParentMessageProto.ParentMessage) obj;

      boolean result = true;
      result = result && getText()
          .equals(other.getText());
      result = result && (hasChildMessage() == other.hasChildMessage());
      if (hasChildMessage()) {
        result = result && getChildMessage()
            .equals(other.getChildMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      if (hasChildMessage()) {
        hash = (37 * hash) + CHILDMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getChildMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.criss.wang.entity.proto.ParentMessageProto.ParentMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.criss.wang.entity.proto.ParentMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.criss.wang.entity.proto.ParentMessage)
        com.criss.wang.entity.proto.ParentMessageProto.ParentMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ParentMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ParentMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.criss.wang.entity.proto.ParentMessageProto.ParentMessage.class, com.criss.wang.entity.proto.ParentMessageProto.ParentMessage.Builder.class);
      }

      // Construct using com.criss.wang.entity.proto.ParentMessageProto.ParentMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        text_ = "";

        if (childMessageBuilder_ == null) {
          childMessage_ = null;
        } else {
          childMessage_ = null;
          childMessageBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ParentMessage_descriptor;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ParentMessageProto.ParentMessage getDefaultInstanceForType() {
        return com.criss.wang.entity.proto.ParentMessageProto.ParentMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ParentMessageProto.ParentMessage build() {
        com.criss.wang.entity.proto.ParentMessageProto.ParentMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ParentMessageProto.ParentMessage buildPartial() {
        com.criss.wang.entity.proto.ParentMessageProto.ParentMessage result = new com.criss.wang.entity.proto.ParentMessageProto.ParentMessage(this);
        result.text_ = text_;
        if (childMessageBuilder_ == null) {
          result.childMessage_ = childMessage_;
        } else {
          result.childMessage_ = childMessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.criss.wang.entity.proto.ParentMessageProto.ParentMessage) {
          return mergeFrom((com.criss.wang.entity.proto.ParentMessageProto.ParentMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.criss.wang.entity.proto.ParentMessageProto.ParentMessage other) {
        if (other == com.criss.wang.entity.proto.ParentMessageProto.ParentMessage.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (other.hasChildMessage()) {
          mergeChildMessage(other.getChildMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.criss.wang.entity.proto.ParentMessageProto.ParentMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.criss.wang.entity.proto.ParentMessageProto.ParentMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any childMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> childMessageBuilder_;
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public boolean hasChildMessage() {
        return childMessageBuilder_ != null || childMessage_ != null;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public com.google.protobuf.Any getChildMessage() {
        if (childMessageBuilder_ == null) {
          return childMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : childMessage_;
        } else {
          return childMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder setChildMessage(com.google.protobuf.Any value) {
        if (childMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          childMessage_ = value;
          onChanged();
        } else {
          childMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder setChildMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (childMessageBuilder_ == null) {
          childMessage_ = builderForValue.build();
          onChanged();
        } else {
          childMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder mergeChildMessage(com.google.protobuf.Any value) {
        if (childMessageBuilder_ == null) {
          if (childMessage_ != null) {
            childMessage_ =
              com.google.protobuf.Any.newBuilder(childMessage_).mergeFrom(value).buildPartial();
          } else {
            childMessage_ = value;
          }
          onChanged();
        } else {
          childMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public Builder clearChildMessage() {
        if (childMessageBuilder_ == null) {
          childMessage_ = null;
          onChanged();
        } else {
          childMessage_ = null;
          childMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public com.google.protobuf.Any.Builder getChildMessageBuilder() {
        
        onChanged();
        return getChildMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getChildMessageOrBuilder() {
        if (childMessageBuilder_ != null) {
          return childMessageBuilder_.getMessageOrBuilder();
        } else {
          return childMessage_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : childMessage_;
        }
      }
      /**
       * <code>.google.protobuf.Any childMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getChildMessageFieldBuilder() {
        if (childMessageBuilder_ == null) {
          childMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getChildMessage(),
                  getParentForChildren(),
                  isClean());
          childMessage_ = null;
        }
        return childMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.criss.wang.entity.proto.ParentMessage)
    }

    // @@protoc_insertion_point(class_scope:com.criss.wang.entity.proto.ParentMessage)
    private static final com.criss.wang.entity.proto.ParentMessageProto.ParentMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.criss.wang.entity.proto.ParentMessageProto.ParentMessage();
    }

    public static com.criss.wang.entity.proto.ParentMessageProto.ParentMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParentMessage>
        PARSER = new com.google.protobuf.AbstractParser<ParentMessage>() {
      @java.lang.Override
      public ParentMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParentMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParentMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParentMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.criss.wang.entity.proto.ParentMessageProto.ParentMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChildMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.criss.wang.entity.proto.ChildMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code com.criss.wang.entity.proto.ChildMessage}
   */
  public  static final class ChildMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.criss.wang.entity.proto.ChildMessage)
      ChildMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChildMessage.newBuilder() to construct.
    private ChildMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChildMessage() {
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChildMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ChildMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ChildMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.criss.wang.entity.proto.ParentMessageProto.ChildMessage.class, com.criss.wang.entity.proto.ParentMessageProto.ChildMessage.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.criss.wang.entity.proto.ParentMessageProto.ChildMessage)) {
        return super.equals(obj);
      }
      com.criss.wang.entity.proto.ParentMessageProto.ChildMessage other = (com.criss.wang.entity.proto.ParentMessageProto.ChildMessage) obj;

      boolean result = true;
      result = result && getText()
          .equals(other.getText());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.criss.wang.entity.proto.ParentMessageProto.ChildMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.criss.wang.entity.proto.ChildMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.criss.wang.entity.proto.ChildMessage)
        com.criss.wang.entity.proto.ParentMessageProto.ChildMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ChildMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ChildMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.criss.wang.entity.proto.ParentMessageProto.ChildMessage.class, com.criss.wang.entity.proto.ParentMessageProto.ChildMessage.Builder.class);
      }

      // Construct using com.criss.wang.entity.proto.ParentMessageProto.ChildMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        text_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.criss.wang.entity.proto.ParentMessageProto.internal_static_com_criss_wang_entity_proto_ChildMessage_descriptor;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ParentMessageProto.ChildMessage getDefaultInstanceForType() {
        return com.criss.wang.entity.proto.ParentMessageProto.ChildMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ParentMessageProto.ChildMessage build() {
        com.criss.wang.entity.proto.ParentMessageProto.ChildMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.criss.wang.entity.proto.ParentMessageProto.ChildMessage buildPartial() {
        com.criss.wang.entity.proto.ParentMessageProto.ChildMessage result = new com.criss.wang.entity.proto.ParentMessageProto.ChildMessage(this);
        result.text_ = text_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.criss.wang.entity.proto.ParentMessageProto.ChildMessage) {
          return mergeFrom((com.criss.wang.entity.proto.ParentMessageProto.ChildMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.criss.wang.entity.proto.ParentMessageProto.ChildMessage other) {
        if (other == com.criss.wang.entity.proto.ParentMessageProto.ChildMessage.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.criss.wang.entity.proto.ParentMessageProto.ChildMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.criss.wang.entity.proto.ParentMessageProto.ChildMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.criss.wang.entity.proto.ChildMessage)
    }

    // @@protoc_insertion_point(class_scope:com.criss.wang.entity.proto.ChildMessage)
    private static final com.criss.wang.entity.proto.ParentMessageProto.ChildMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.criss.wang.entity.proto.ParentMessageProto.ChildMessage();
    }

    public static com.criss.wang.entity.proto.ParentMessageProto.ChildMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChildMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChildMessage>() {
      @java.lang.Override
      public ChildMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChildMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChildMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChildMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.criss.wang.entity.proto.ParentMessageProto.ChildMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_criss_wang_entity_proto_ParentMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_criss_wang_entity_proto_ParentMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_criss_wang_entity_proto_ChildMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_criss_wang_entity_proto_ChildMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ParentMessage.proto\022\033com.criss.wang.en" +
      "tity.proto\032\031google/protobuf/any.proto\"I\n" +
      "\rParentMessage\022\014\n\004text\030\001 \001(\t\022*\n\014childMes" +
      "sage\030\002 \001(\0132\024.google.protobuf.Any\"\034\n\014Chil" +
      "dMessage\022\014\n\004text\030\001 \001(\tB\024B\022ParentMessageP" +
      "rotob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_com_criss_wang_entity_proto_ParentMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_criss_wang_entity_proto_ParentMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_criss_wang_entity_proto_ParentMessage_descriptor,
        new java.lang.String[] { "Text", "ChildMessage", });
    internal_static_com_criss_wang_entity_proto_ChildMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_criss_wang_entity_proto_ChildMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_criss_wang_entity_proto_ChildMessage_descriptor,
        new java.lang.String[] { "Text", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
